### ISSUE TITLE
Juel is not thread safe on ValueExpression.getValue and ValueExpression.setValue due to shared context

### ISSUE THREAD

**Issue by dpwspoon** [beckchr/juel#87]
In AstIdentifier
```
		Object result = context.getELResolver().getValue(context, null, name);
		if (!context.isPropertyResolved()) {
			throw new PropertyNotFoundException(LocalMessages.get("error.identifier.property.notfound", name));
		}
```

can throw the PropertyNotFoundException even when the result is correctly populated.  This can occur when multiple threads are calling get and setValue.  It maybe better if context.getELResolver().getValue(context, null, name) threw the PropertyNotFoundException directly.

Here is the stack trace from when this was observed
```
javax.el.PropertyNotFoundException: Cannot resolve identifier 'randO'
	at de.odysseus.el.tree.impl.ast.AstIdentifier.eval(AstIdentifier.java:93)
	at de.odysseus.el.tree.impl.ast.AstEval.eval(AstEval.java:51)
	at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:31)
	at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
	at org.kaazing.k3po.driver.behavior.handler.codec.WriteExpressionEncoder.encode(WriteExpressionEncoder.java:50)
	at org.kaazing.k3po.driver.behavior.handler.command.WriteHandler.invokeCommand(WriteHandler.java:52)
	at org.kaazing.k3po.driver.behavior.handler.command.AbstractCommandHandler$1.operationComplete(AbstractCommandHandler.java:48)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:413)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.k3po.driver.netty.channel.CompositeChannelFuture$NotifyingListener.operationComplete(CompositeChannelFuture.java:204)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.k3po.driver.behavior.handler.event.ConnectedHandler.channelConnected(ConnectedHandler.java:36)
	at org.kaazing.k3po.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:37)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:42)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:161)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:107)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:96)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.kaazing.k3po.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:96)
	at org.kaazing.k3po.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:157)
	at org.kaazing.k3po.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:32)
	at org.jboss.netty.channel.Channels.fireChannelConnected(Channels.java:227)
	at org.jboss.netty.channel.socket.nio.NioWorker$RegisterTask.run(NioWorker.java:162)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Is this code actively maintained, and would a pull request be merged/released?

Is this a usage error, currently we use a global context for many expressions.  Should a expression and context have a one to one correlation, or a context per a single thread?

**Comment by beckchr** [comment]
It's the nature of the context... Thread safe across contexts, but not within the same context. From the `ELContext` documentation at Oracle:

> Because it stores state during expression evaluation, an ELContext object is not thread-safe. Care should be taken to never share an ELContext instance between two or more threads.
